database:
  host: localhost

spring:
  application.name: kotlin-starter
  profiles.active: default
  datasource:
    url: jdbc:postgresql://${database.host}:5432/starter
    platform: postgresql
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: validate
    open-in-view: true
---
spring:
  profiles: default
---
spring:
  profiles: test
---
spring:
  profiles: production

management:
  metrics:
    export:
      statsd:
        host: ${DOGSTATSD_HOST}
        port: 8125
